"""Build, write, and (optionally) file GitHub-style tickets."""
from __future__ import annotations

import json
import base64
from http.client import InvalidURL
from urllib.parse import urlsplit
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import HTTPRedirectHandler, Request, build_opener

from hound_agent.models import Artifacts, RootCause, Ticket, Triage
from hound_agent.output.report import _atomic_write, ensure_outdir
from hound_agent.output.markdown import escape_code, escape_text

LABELS = {
    "severity": "severity:{s}",
    "component": "component:{c}",
}


class _NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


urlopen = build_opener(_NoRedirect()).open


class GithubError(Exception):
    """Raised when GitHub issue creation fails."""


class JiraError(Exception):
    """Raised when Jira issue creation fails."""


class GitlabError(Exception):
    """Raised when GitLab issue creation fails."""


def build_ticket(
    artifacts: Artifacts,
    root_cause: RootCause,
    triage: Triage,
) -> Ticket:
    headline = artifacts.summary or "CI/CD failure"
    title = " ".join(f"[{triage.component}] {headline}".split())[:120]
    if triage.is_duplicate_of:
        title = f"Duplicate: {title}"

    safe_msg = artifacts.message.replace("```", "'''") if artifacts.message else ""
    body = [
        "## Summary",
        escape_text(artifacts.summary or "No summary extracted."),
        "",
        "## Failure details",
        f"- **Stage**: {artifacts.stage}",
        f"- **Kind**: {artifacts.kind}",
        "",
        "### Log message",
        "```",
        safe_msg,
        "```",
        "",
        "### Stacktrace",
    ]
    if artifacts.frames:
        for frame in artifacts.frames[:10]:
            loc = f"{escape_code(frame.file)}:{frame.line}"
            if frame.function:
                loc += f" ({escape_code(frame.function)})"
            body.append(f"- `{loc}`")
            if frame.code:
                body.append("  ```")
                body.extend("  " + line.replace("```", "'''") for line in frame.code.splitlines())
                body.append("  ```")
    else:
        body.append("- (none)")

    if artifacts.failed_tests:
        body += ["", "### Failed tests"]
        for tst in artifacts.failed_tests[:10]:
            body.append(f"- `{escape_code(tst.name)}`" + (f" - {escape_text(tst.assertion)}" if tst.assertion else ""))

    if artifacts.git.head:
        body += ["", "### Repo context"]
        if artifacts.git.branch:
            body.append(f"- **Branch**: `{escape_code(artifacts.git.branch)}`")
        body.append(f"- **HEAD**: `{escape_code(artifacts.git.head[:12])}`")
    if artifacts.git.owners:
        body.append(f"- **Owners**: {', '.join(escape_text(owner) for owner in artifacts.git.owners)}")

    if any(vars(artifacts.run).values()):
        body += ["", "### CI context"]
        if artifacts.run.run_url:
            body.append(f"- **Run**: {escape_text(artifacts.run.run_url)}")
        if artifacts.run.job_name:
            body.append(f"- **Job**: {escape_text(artifacts.run.job_name)}")
        if artifacts.run.pr_number:
            body.append(f"- **PR**: #{escape_text(artifacts.run.pr_number)}")
    if any(vars(artifacts.deployment).values()):
        body += ["", "### Deployment context"]
        for key in ("platform", "environment", "namespace", "target", "release", "revision", "artifact", "outcome", "recovery"):
            value = getattr(artifacts.deployment, key)
            if value:
                body.append(f"- **{key.title()}**: {escape_text(value)}")

    if triage.flaky_suspect:
        body += [
            "",
            "> :warning: **Flaky suspect** — this test failed and then passed on a rerun. "
            "Investigate determinism before fixing the reported assertion.",
        ]
    if triage.recurring_incident:
        body += ["", f"> **Recurring incident**: seen {triage.occurrence_count} times."]

    body += [
        "",
        "## Root cause",
        f"**Hypothesis**: {escape_text(root_cause.hypothesis)}",
        "",
        "**Fix suggestion**:",
        escape_text(root_cause.fix_suggestion),
        "",
        f"_Analysis engine: {escape_text(root_cause.engine)}" + (f" / model `{escape_code(root_cause.model)}`" if root_cause.model else "") + "_",
        "",
        "## Labels",
        f"- {escape_text(LABELS['severity'].format(s=triage.severity))}",
        f"- {escape_text(LABELS['component'].format(c=triage.component))}",
        "",
        "<!-- generated by Hound Agent; review before filing -->",
    ]

    return Ticket(
        title=title,
        body_md="\n".join(body),
        labels=[
            LABELS["severity"].format(s=triage.severity),
            LABELS["component"].format(c=triage.component),
        ],
    )


def write_ticket(ticket: Ticket, outdir: str | Path) -> Path:
    path = ensure_outdir(outdir) / "ticket.md"
    _atomic_write(path, f"# {escape_text(ticket.title)}\n\n{ticket.body_md}\n")
    return path


def create_github_ticket(
    ticket: Ticket,
    repo: str,
    token: str,
    api_base: str = "https://api.github.com",
) -> str:
    """Create a GitHub issue via REST API. Returns the issue HTML URL."""
    if not repo or not token:
        raise GithubError("GH_REPO and GH_TOKEN are required for --gh")
    if "/" not in repo:
        raise GithubError(f"GH_REPO must be owner/name, got {repo!r}")
    parsed = urlsplit(api_base)
    local_hosts = {"localhost", "127.0.0.1", "::1"}
    if parsed.scheme not in {"https", "http"} or not parsed.hostname:
        raise GithubError(f"Invalid GH_API_BASE: {api_base}")
    if parsed.scheme != "https" and parsed.hostname not in local_hosts:
        raise GithubError(f"Insecure non-HTTPS GH_API_BASE disallowed: {api_base}")

    owner, name = repo.split("/", 1)
    url = f"{api_base.rstrip('/')}/repos/{owner}/{name}/issues"
    payload = json.dumps(
        {"title": ticket.title, "body": ticket.body_md, "labels": ticket.labels}
    ).encode("utf-8")
    request = Request(
        url,
        data=payload,
        method="POST",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
        },
    )
    try:
        with urlopen(request, timeout=30) as resp:  # noqa: S310 - user-supplied API base
            data = json.loads(resp.read().decode("utf-8"))
    except (HTTPError, URLError, OSError, InvalidURL, json.JSONDecodeError) as exc:
        raise GithubError(str(exc)) from exc
    if not isinstance(data, dict):
        raise GithubError("GitHub API returned a non-object response")
    html_url = data.get("html_url")
    if not isinstance(html_url, str) or not html_url:
        raise GithubError("GitHub API returned no html_url")
    return html_url


def create_jira_ticket(
    ticket: Ticket,
    url: str,
    project: str,
    token: str,
    email: str = "",
) -> str:
    """Create a Jira issue via REST API v2. Returns the issue key."""
    if not url or not project or not token:
        raise JiraError("JIRA_URL, JIRA_PROJECT, and JIRA_TOKEN are required for --jira")
    parsed = urlsplit(url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise JiraError(f"Insecure non-HTTPS JIRA_URL disallowed: {url}")

    endpoint = f"{url.rstrip('/')}/rest/api/2/issue"
    payload = json.dumps(
        {
            "fields": {
                "project": {"key": project},
                "summary": ticket.title,
                "description": ticket.body_md,
                "labels": ticket.labels,
            }
        }
    ).encode("utf-8")
    authorization = f"Bearer {token}"
    if email:
        encoded = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
        authorization = f"Basic {encoded}"
    request = Request(
        endpoint,
        data=payload,
        method="POST",
        headers={
            "Authorization": authorization,
            "Content-Type": "application/json",
        },
    )
    try:
        with urlopen(request, timeout=30) as resp:  # noqa: S310 - user-supplied URL
            data = json.loads(resp.read().decode("utf-8"))
    except (HTTPError, URLError, OSError, InvalidURL, json.JSONDecodeError) as exc:
        raise JiraError(str(exc)) from exc
    if not isinstance(data, dict):
        raise JiraError("Jira API returned a non-object response")
    key = data.get("key")
    if not isinstance(key, str) or not key:
        raise JiraError("Jira API returned no issue key")
    return f"{url.rstrip('/')}/browse/{key}"


def create_gitlab_ticket(
    ticket: Ticket,
    url: str,
    project: str,
    token: str,
) -> str:
    """Create a GitLab issue via REST API v4. Returns the issue web URL."""
    if not url or not project or not token:
        raise GitlabError("GITLAB_URL, GITLAB_PROJECT, and GITLAB_TOKEN are required for --gitlab")
    parsed = urlsplit(url)
    if parsed.scheme != "https" or not parsed.netloc:
        raise GitlabError(f"Insecure non-HTTPS GITLAB_URL disallowed: {url}")

    from urllib.parse import quote

    endpoint = f"{url.rstrip('/')}/api/v4/projects/{quote(project, safe='')}/issues"
    payload = json.dumps(
        {"title": ticket.title, "description": ticket.body_md, "labels": ",".join(ticket.labels)}
    ).encode("utf-8")
    request = Request(
        endpoint,
        data=payload,
        method="POST",
        headers={
            "PRIVATE-TOKEN": token,
            "Content-Type": "application/json",
        },
    )
    try:
        with urlopen(request, timeout=30) as resp:  # noqa: S310 - user-supplied URL
            data = json.loads(resp.read().decode("utf-8"))
    except (HTTPError, URLError, OSError, InvalidURL, json.JSONDecodeError) as exc:
        raise GitlabError(str(exc)) from exc
    if not isinstance(data, dict):
        raise GitlabError("GitLab API returned a non-object response")
    web_url = data.get("web_url")
    if not isinstance(web_url, str) or not web_url:
        raise GitlabError("GitLab API returned no web_url")
    return web_url
